### ISSUE TITLE
examples fail

### ISSUE THREAD

**Issue by iqualfragile** [phsym/rust-sctp#4]
The examples listener and one_to_many fail.
listener fails with InvalidInput.
one_to_many fails with NotConnected.
which is strange as it should wait for the first packet received is the socket maybe created as STREAM instead of SEQPACKET?

**Comment by phsym** [comment]
Indeed. This library is experimental and started as a way for me to learn unsafe rust and C binding

**Comment by phsym** [comment]
Should be better now.
You were right, `SctpEndpoint::bind` created the socket as `STREAM` instead of `SEQPACKET`.
Also, `SctpEndpoint::bind` and `SctpListener::bind` were not calling `listen()` on the underlying socket

**Comment by iqualfragile** [comment]
thanks, this is great news :)
